
name: Test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-18.04]
      
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1

      - name: Test
        run: swift test -v --enable-test-discovery --enable-code-coverage --sanitize=thread